import type { Alpine as AlpineType, interceptor } from 'alpinejs';

declare global {
  interface Window {
    Alpine: AlpineType;
    ComparisonManager?: any;
    ReconciliationManager?: any;
  }

  var Alpine: AlpineType;

  // Domain Models
  interface Lease {
    batch_id: number;
    batch_number: number;
    project_id: string;
    leased_until: string;
    is_leased_by_you: boolean;
  }

  interface Project {
    project_id: string;
    name: string;
    resolved_clusters?: number;
    total_clusters?: number;
  }

  type TagCategory =
    | 'ARTIST'
    | 'CONTRIBUTOR'
    | 'COPYRIGHT'
    | 'CHARACTER'
    | 'SPECIES'
    | 'GENERAL'
    | 'META'
    | 'LORE'
    | 'INVALID';

  type PostRating =
    | 's'
    | 'q'
    | 'e';

  interface TagObj {
    name: string;
    category: TagCategory;
  }

  interface ClusterPost {
    post_id: number;
    cluster_id: number;
    rating: PostRating;
    pool_ids: number[];
    parent_id: number | null;
    is_flagged: boolean;
    is_deleted: boolean;
    tags: string[];
    image_width: number;
    image_height: number;
    image_format: string;
    image_quality: number;
    fileUrl?: string;
    description?: string;
    sources?: string[];
    locked_tags?: string[];
    _tagsSignature?: string;
    _sortedTags?: Array<TagObj>;
  }

  interface ClusterPair {
    a: ClusterPost;
    b: ClusterPost;
    relationship?: string | null;
  }

  interface Cluster {
    cluster_id: number;
    cluster_index: number;
    note: string | null;
    is_resolved: boolean;
    manual_resolution: boolean;
    posts: ClusterPost[];
    collapsed?: boolean;
    is_blacklisted?: boolean;
    matched_rule?: string | null;
    canonical_rating?: PostRating;
    isRefreshing?: boolean;
    pairs?: ClusterPair[];
    default_type?: string;
    _fetchedPosts?: Map<number, string>;
  }

  interface Batch {
    batch_id: number;
    project_id: string;
    batch_number: number;
    status: string;
    leased_until: string | null;
    is_leased_by_you: boolean;
    resolved_count: number;
    total_clusters: number;
    clusters: Cluster[];
    isRefreshing?: boolean;
    isClaiming?: boolean;
    isRevoking?: boolean;
  }

  interface E621User {
    username: string;
    apiKey: string;
    id: number;
  }

  interface TagSearchResult {
    name: string;
    category: TagCategory;
    count: number;
    aliasedFrom?: string
  }
  type ResolutionPost = import('./static/js/resolution.js').ResolutionPost;

  /**
   * Native Alpine component contract generated by the resolutionManager factory.
   */
  interface ResolutionManagerComponent {
    cluster: Cluster;
    graphs: ResolutionGraph[];
    relations: Map<string, GraphRelation>;
    posts: Map<number, ResolutionPost>;

    /** Lifecycle hook called automatically by Alpine */
    init(): Promise<void>;

    /** Fetches remote details and initializes internal post wrappers */
    initializePosts(): Promise<void>;

    /** Ensures a default duplicate graph exists for the cluster */
    ensureDefaultDuplicateGraph(): void;

    /** Retrieves a ResolutionPost instance by ID */
    getPost(postId: number): ResolutionPost | undefined;

    /**
     * Collapses a duplicate graph down to a single canonical post ID
     * and updates any variant graphs referencing those duplicate posts.
     */
    resolveDuplicateGraph(graph: ResolutionGraph): void;

    /** Helper to construct a standard pairwise string key "minId:maxId" */
    _getRelationKey(a: number, b: number): string;

    /** Marks a post as unknown (e.g., missing fileUrl) */
    markUnknown(id: number): void;

    /** Signals a relation of a specific type between two post IDs */
    addGraphEdge(type: GraphType, a: number, b: number, superiorId: number | null): void;

    /**
     * Recalculates transitive connections (duplicates/variants) and replicates
     * unrelated links across connected components into `this.relations`.
     */
    recalculateDerivedRelations(): void;

    /** Finds the next pair of post IDs needing comparison to resolve relationships */
    getNextPair(): [number, number] | false;

    /** Clears all recorded graphs and relations */
    clearGraphs(): void;
  }
}

export { };