import type { Alpine as AlpineType, interceptor } from 'alpinejs';

declare global {
  interface Window {
    Alpine: AlpineType;
    ComparisonManager?: any;
    ReconciliationManager?: any;
    ensureClusterPostsInfo?: (posts: ClusterPost[]) => Promise<void>;
  }

  var Alpine: AlpineType;

  // Domain Models
  interface Lease {
    batchId: number;
    batchNumber: number;
    projectId: string;
    leasedUntil: string;
    isLeasedByYou: boolean;
  }

  interface Project {
    projectId: string;
    name?: string;
    title?: string;
    description?: string;
    instructionsHtml?: string;
    resolvedClusters?: number;
    totalClusters?: number;
  }

  type TagCategory =
    | 'ARTIST'
    | 'CONTRIBUTOR'
    | 'COPYRIGHT'
    | 'CHARACTER'
    | 'SPECIES'
    | 'GENERAL'
    | 'META'
    | 'LORE'
    | 'INVALID';

  type PostRating =
    | 's'
    | 'q'
    | 'e';

  interface TagObj {
    name: string;
    category: TagCategory;
  }

  interface ClusterPost {
    postId: number;
    clusterId: number;
    rating: PostRating;
    poolIds: number[];
    parentId: number | null;
    isFlagged: boolean;
    isDeleted: boolean;
    tags: string[];
    imageWidth: number;
    imageHeight: number;
    imageFormat: string;
    imageQuality: number;
    fileUrl?: string | null;
    previewUrl?: string | null;
    description?: string;
    sources?: string[];
    lockedTags?: string[];
    _tagsSignature?: string;
    _sortedTags?: Array<TagObj>;
  }

  interface ClusterPair {
    a: ClusterPost;
    b: ClusterPost;
    relationship?: string | null;
  }

  interface TopologyPost {
    postId: number;
    isDuplicate: boolean;
    isFlagged: boolean;
    isDeleted: boolean;
    parentId: number | null;
    poolIds: number[];
    rating: PostRating | string;
  }

  interface DuplicateSubgraph {
    canonicalPostId: number;
    posts: TopologyPost[];
  }

  interface VariantSubgraph {
    posts: TopologyPost[];
    duplicateSubgraphs: DuplicateSubgraph[];
  }

  interface ClusterTopology {
    variantSubgraphs: VariantSubgraph[];
    duplicateSubgraphs: DuplicateSubgraph[];
    standalonePosts: TopologyPost[];
    totalPosts: number;
    isBlacklisted: boolean;
    isResolved: boolean;
  }

  interface Cluster {
    clusterId: number;
    clusterIndex: number;
    note: string | null;
    isResolved: boolean;
    manualResolution: boolean;
    posts: ClusterPost[];
    topology?: ClusterTopology;
    collapsed?: boolean;
    isBlacklisted?: boolean;
    matchedRule?: string | null;
    canonicalRating?: PostRating;
    isRefreshing?: boolean;
    pairs?: ClusterPair[];
    defaultType?: string;
    _fetchedPosts?: Map<number, string>;
  }

  interface Batch {
    batchId: number;
    projectId: string;
    batchNumber: number;
    status: string;
    leasedUntil: string | null;
    isLeasedByYou: boolean;
    resolvedCount: number;
    totalClusters: number;
    clusters: Cluster[];
    isRefreshing?: boolean;
    isClaiming?: boolean;
    isRevoking?: boolean;
  }

  interface E621User {
    username: string;
    apiKey: string;
    id: number;
  }

  interface TagSearchResult {
    name: string;
    category: TagCategory;
    count: number;
    aliasedFrom?: string
  }

  interface ClaimBatchResponse {
    batchId: number;
    leasedUntil: string;
    detail?: string;
  }

  type GraphType = 'duplicate' | 'variant' | 'unrelated' | 'unknown';

  interface ResolutionGraph {
    id?: string;
    type: GraphType;
    posts: Set<number>;
    head?: number | null;
  }

  interface GraphRelation {
    a?: number;
    b?: number;
    type: GraphType;
    superiorId?: number | null;
  }

  type ResolutionPost = import('./resolution.js').ResolutionPost;

  /**
   * Native Alpine component contract generated by the resolutionManager factory.
   */
  interface ResolutionManagerComponent {
    cluster: Cluster;
    graphs: ResolutionGraph[];
    relations: Map<string, GraphRelation>;
    posts: Map<number, ResolutionPost>;
    activeComparison?: any;
    activeReconciliation?: any;

    /** Lifecycle hook called automatically by Alpine */
    init(): Promise<void>;

    /** Fetches remote details and initializes internal post wrappers */
    initializePosts(): Promise<void>;

    /** Preloads known duplicate and variant relations from existing cluster metadata */
    preloadKnownRelations(): void;

    /** Ensures a default duplicate graph exists for the cluster */
    ensureDefaultDuplicateGraph(): void;

    /** Retrieves a ResolutionPost instance by ID */
    getPost(postId: number): ResolutionPost | undefined;

    /**
     * Collapses a duplicate graph down to a single canonical post ID
     * and updates any variant graphs referencing those duplicate posts.
     */
    resolveDuplicateGraph(graph: ResolutionGraph): void;

    /** Helper to construct a standard pairwise string key "minId:maxId" */
    _getRelationKey(a: number, b: number): string;

    /** Marks a post as unknown (e.g., missing fileUrl) */
    markUnknown(id: number): void;

    /** Signals a relation of a specific type between two post IDs */
    addGraphEdge(type: GraphType, a: number, b: number, superiorId: number | null): void;

    /** Flattens a variant graph hierarchy so all children have parentId set to rootParentId */
    flattenVariantHierarchy(variantGraph: ResolutionGraph, rootParentId: number): void;

    /**
     * Recalculates transitive connections (duplicates/variants) and replicates
     * unrelated links across connected components into `this.relations`.
     */
    recalculateDerivedRelations(): void;

    /** Finds the next pair of post IDs needing comparison to resolve relationships */
    getNextPair(): [number, number] | false;

    /** Clears all recorded graphs and relations */
    clearGraphs(): void;

    /** Clears working graph state and resets all post instances back to original values */
    resetClusterWork(): void;
  }
}

export { };